# Generated by Django 5.0.2 on 2024-02-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
