# Generated by Django 5.0.2 on 2024-02-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0003_remove_transaction_stock_investment_delete_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='purchase_price',
        ),
    ]
