# Generated by Django 5.0.2 on 2024-02-22 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0004_remove_investment_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
