# Generated by Django 5.0.2 on 2024-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0005_alter_investment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='transaction_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4),
        ),
    ]
