# Generated by Django 5.0.2 on 2024-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0006_alter_investment_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='price_difference_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
