# Generated by Django 5.0.2 on 2024-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0010_monthlyperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyperformance',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
