# Generated by Django 5.0.2 on 2024-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0011_alter_monthlyperformance_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyperformance',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
