# Generated by Django 5.0.2 on 2024-03-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0012_monthlyperformance_value_portfolio_current_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='price_difference_percentage',
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_management.portfolio')),
            ],
        ),
    ]
