# Generated by Django 5.0.2 on 2024-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0014_remove_holding_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='price_difference_percentage',
        ),
        migrations.AddField(
            model_name='holding',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
