# Generated by Django 5.0.2 on 2024-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0015_remove_investment_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
