# Generated by Django 5.0.2 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0017_remove_investment_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='capital_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
