# Generated by Django 5.0.2 on 2024-03-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0018_portfolio_capital_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='capital_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
