# Generated by Django 5.0.2 on 2024-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0019_holding_capital_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyperformance',
            name='capital_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
