# Generated by Django 5.0.3 on 2024-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0020_monthlyperformance_capital_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
