# Generated by Django 5.0.3 on 2024-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0021_investment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD')], max_length=3),
        ),
    ]
